const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const Schema = mongoose.Schema;

const schema = new Schema({
    contract_type: String,
    contract_id: String,
    trade_date: String,
    buyer: String,
    seller: String,
    port: String,
    product: String,
    product_comments: String,
    quantity: String,
    percentage: String,
    product_units: String,
    b_s_option: String,
    delivery_date: String,
    value: String,
    terms: String,
    nomination: String,
    price: String,
    unit: String,
    price_opt_1: String,
    price_opt_2: String,
    price_opt_1_cmt: String,
    price_opt_2_cmt: String,
    comments: String,
    pricing_schedule: String,
    pricing: String,
    payment: String,
    credit: String,
    quantity_determination: String,
    quality_determination: String,
    quality_adjustment: String,
    inspection: String,
    demurrage: String,
    laytime: String,
    ship: String,
    claims: String,
    charges: String,
    law_arbitration: String,
    other: String,
    confirmation_due_date: String,
    confirmation_due_time: String,
    deal_status: String,
    addedBy: { type: Schema.Types.ObjectId, ref: 'User'},
	addedOn: { type: Date, default: Date.now }
})
module.exports = mongoose.model('dealRegistry', schema)
